translate deutsch strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Dein Ziel in diesen Rätseln ist es, das gesamte Raster mit grünen und schwarzen Quadraten zu füllen.\n\nOben links vom Raster befinden sich Zahlen. Diese Zahlen geben die Anzahl der grünen Quadrate in der jeweiligen Zeile und Spalte an.\n\nBeispiel: Wenn neben der Zeile eine 3 steht, bedeutet dies, dass sich irgendwo in dieser Zeile drei grüne (verbundene) Quadrate befinden. Dasselbe gilt für Spalten, basierend auf den Zahlen oben im Rätsel. Eine 2 oben in einer Spalte bedeutet, dass sich in dieser Spalte zwei grüne Quadrate befinden, die vertikal verlaufen."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Du wirst feststellen, dass einige Zeilen/Spalten 2 Zahlen haben.\n\nWenn du 2 1 siehst, bedeutet das, dass sich irgendwo in dieser Zeile eine Reihe von genau 2 grünen Quadraten befindet, gefolgt von 1 oder mehr schwarzen Quadraten, gefolgt von 1 grünen Quadrat.\n\nVor oder nach den grünen Quadraten können schwarze Quadrate stehen – nur die Reihen der grünen Quadrate werden gezählt."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Klicke mit der linken Maustaste auf ein Feld, um es grün zu markieren. Klicke mit der rechten Maustaste, um es schwarz zu markieren.\n\nIn unserem System stehen die schwarzen Felder für leere oder unausgefüllte Felder und die grünen Felder für codierte oder ausgefüllte Felder.\n\nDu musst die leeren Felder nicht ausfüllen, wenn du dies nicht möchtest. Dies ist für das Lösen des Rätsels nicht erforderlich."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "Es wird dringend empfohlen, niemals zu raten. Nur Felder, die logisch bestimmt werden können, sollten kodiert oder grün ausgefüllt werden.\n\nEin einziger Fehler kann leicht zu Ungenauigkeiten im gesamten Rätsel führen.\n\nEinfache Rätsel lassen sich in der Regel lösen, indem man sich auf eine Zeile/Spalte konzentriert und die Logik herausfindet. Dann geht man zur nächsten Zeile und zur nächsten über, bis man alle grünen Felder ausgefüllt hat."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Einige anspruchsvollere Rätsel erfordern möglicherweise auch mehrere Arten des Denkens, die mehr als eine Zeile (oder Spalte) umfassen.\n\nDu denkst vielleicht, du hättest die richtige Antwort für eine Zeile, aber deine Antwort funktioniert möglicherweise nicht für eine sich überschneidende Spalte. Das Auflösen dieser Widersprüche ist der Schlüssel zum Lösen komplizierterer Rätsel.\n\nWenn eine Zelle kein codiertes/grünes Quadrat sein kann, weil eine andere Zelle einen Fehler erzeugen würde, solltest sie ein schwarzes/leeres Quadrat sein – und umgekehrt.\n\nWenn du von deiner Lösung überzeugt bist, klicke auf das Häkchen, um das Programm zur Codeüberprüfung einzureichen."

