translate portuguese strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Seu objetivo nesses quebra-cabeças é preencher toda a grade com quadrados verdes e pretos.\n\nNa parte superior esquerda da grade há números. Esses são os números indicadores que mostram o número de quadrados verdes nesta fileira e coluna específicas.\n\nExemplo. Se a fileira tiver um '3' ao lado, quer dizer que haverá um conjunto de três quadrados verdes conectados em algum lugar dessa fileira. O mesmo vale para as colunas baseado no número acima do quebra-cabeça. Um '2' acima da coluna significa que nessa coluna há um conjunto de dois quadrados verdes verticalmente."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Você perceberá que certas fileiras/colunas possuem 2 números.\n\nSe vir '2 1', quer dizer que em algum lugar dessa linha haverá um grupo de exatamente dois quadrados verdes, seguidos por 1 ou mais quadrados pretos, seguidos por 1 quadrado verde.\n\nPode haver quadrados pretos antes ou depois de quadrados verdes - apenas grupos de quadrados verdes contam."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Clique com o botão esquerdo em um quadrado para deixá-lo verde. Clique com o botão direito para deixá-lo preto.\n\nNo nosso sistema, quadrados pretos representam vazio, ou quadrados sem nada, e quadrados verdes representam código, ou quadrados preenchidos.\n\Não é necessário marca os quadrados vazios se não quiser. Não é necessário para resolver o quebra-cabeças."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "É altamente recomendado nunca adivinhar. Apenas quadrados que podem ser determinados por lógica devem ser programados ou preenchidos de verde.\n\nÉ fácil um único erro causar problemas no quebra-cabeças inteiro.\n\nQuebra-cabeças simples normalmente podem ser resolvidos descobrindo a lógica por trás e focando em uma única fileira/coluna por vez. Em seguida vá para a próxima fileira e a próxima, até preencher todos os quadrados verdes."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Certos quebra-cabeças mais difíceis também podem precisar de vários tipos de lógica que incluem mais de uma fileira (ou coluna).\n\nVocê pode achar que tem a solução correta para uma fileira, mas a sua resposta pode não funcionar para a coluna que cruza. Solucionar essas contradições é importante para solucionar quebra-cabeças mais complicados.\n\nQuando uma célula não pode se tornar um quadrado programado/verde porque outra célula produziria um erro, deve ser um quadrado preto/vazio - e vice-versa.\n\nQuando acreditar que tem a solução, clique no tique para submeter o programa para revisão de código."

