translate french strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Ton objectif dans ces puzzles est de remplir toute la grille avec des carrés verts et noirs.\n\nAu-dessus et à gauche de la grille se trouvent des nombres. Ce sont les indicateurs qui t’indiquent le nombre de carrés verts dans chaque ligne et colonne.\n\nExemple : si une ligne a un '3' à côté, cela signifie qu’il y aura un groupe de trois carrés verts (connectés) quelque part dans cette ligne. C’est la même chose pour les colonnes, selon les nombres en haut du puzzle. Un '2' en haut d’une colonne signifie que dans cette colonne, il y a un groupe de deux carrés verts alignés verticalement."
    
    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Tu remarqueras que certaines lignes ou colonnes ont 2 nombres.\n\nSi tu vois '2 1', cela veut dire que quelque part dans cette ligne, il y aura une suite de 2 carrés verts exactement, suivie d’un ou plusieurs carrés noirs, puis d’un carré vert.\n\nIl peut y avoir des carrés noirs avant ou après les carrés verts – seules les suites de carrés verts sont comptées."
    
    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Clique gauche sur un carré pour le rendre vert. Clique droit pour le marquer en noir.\n\nDans notre système, les carrés noirs représentent les cases vides et les carrés verts sont les cases codées ou remplies.\n\nTu n’as pas besoin de marquer toutes les cases vides si tu ne veux pas. Ce n’est pas obligatoire pour résoudre le puzzle."
    
    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "Il est fortement conseillé de ne jamais deviner. Seules les cases déterminées par la logique doivent être codées ou remplies en vert.\n\nUne seule erreur peut facilement créer des incohérences dans tout le puzzle.\n\nLes puzzles simples se résolvent généralement en raisonnant sur une ligne ou une colonne à la fois. Ensuite, passe à la suivante jusqu’à ce que tu aies rempli tous les carrés verts."
    
    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Certains puzzles plus difficiles peuvent aussi demander plusieurs types de raisonnement impliquant plus d’une ligne (ou colonne).\n\nTu pourrais penser avoir la bonne réponse pour une ligne, mais ta solution peut bloquer sur une colonne croisée. Résoudre ces contradictions est la clé pour avancer dans les puzzles compliqués.\n\nQuand une case ne peut pas être verte/codée parce qu’une autre créerait une erreur, elle doit être noire/vide – et inversement.\n\nQuand tu es sûr de ta solution, clique sur la coche pour soumettre ton programme à la relecture."

#Translate by BlackViper_

