translate italian strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Il tuo obiettivo in questi puzzle è riempire l'intera griglia con quadrati verdi e neri.\n\nSopra e a sinistra della griglia ci sono dei numeri. Questi sono i numeri indicatori che ti dicono il numero di quadrati verdi in quella specifica riga e colonna.\n\nEsempio. Se la riga ha un '3' accanto, significa che ci sarà un gruppo di tre quadrati verdi (collegati) da qualche parte in quella riga. Lo stesso vale per le colonne basandosi sui numeri in cima al puzzle. Un '2' in cima a una colonna significa che in quella colonna c'è un gruppo di due quadrati verdi che corrono verticalmente."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Noterai che alcune righe/colonne hanno 2 numeri.\n\nSe vedi '2 1', ti dice che da qualche parte in quella linea ci sarà una sequenza di esattamente 2 quadrati verdi, seguita da 1 o più quadrati neri, seguita da 1 quadrato verde.\n\nPotrebbero esserci quadrati neri prima o dopo i quadrati verdi - vengono contate solo le sequenze di quadrati verdi."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Clicca col tasto sinistro su un quadrato per renderlo verde. Clicca col tasto destro per segnarlo di nero.\n\nNel nostro sistema, i quadrati neri rappresentano i quadrati vuoti o bianchi e i quadrati verdi sono i quadrati codificati o riempiti.\n\nNon devi riempire i quadrati vuoti segnalandoli se non vuoi. Non è necessario per risolvere il puzzle."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "È fortemente consigliato di non tirare mai a indovinare. Solo i quadrati che possono essere determinati dalla logica dovrebbero essere codificati o riempiti di verde.\n\nÈ facile che un singolo errore causi imprecisioni in tutto il puzzle.\n\nI puzzle semplici possono solitamente essere risolti capendo il ragionamento concentrandosi su una singola riga/colonna alla volta. Poi passa alla riga successiva e alla successiva finché non hai riempito tutti i quadrati verdi."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Alcuni puzzle più impegnativi potrebbero anche richiedere diversi tipi di ragionamento che includono più di una riga (o colonna).\n\nPotresti pensare di avere la risposta corretta per una riga, ma la tua risposta potrebbe non funzionare per una colonna che si interseca. Risolvere queste contraddizioni è la chiave per risolvere puzzle più complicati.\n\nQuando una cella non può essere un quadrato codificato/verde perché un'altra cella produrrebbe un errore, dovrebbe essere un quadrato nero/vuoto - e viceversa.\n\nQuando sei sicuro della tua soluzione, clicca sul segno di spunta per inviare il programma per la revisione del codice."

