translate spanish strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Su objetivo en estos rompecabezas es llenar toda la cuadrícula con cuadrados verdes y negros. \nEncima y a la izquierda de la cuadrícula hay números. Estos son los números indicadores que le dicen el número de cuadrados verdes en esa fila y columna específicas. Si la fila tiene un '3' al lado, significa que habrá un conjunto de tres cuadrados verdes (conectados) en algún lugar de esa fila. Lo mismo ocurre con las columnas basadas en los números de la parte superior del puzzle. Un '2' en la parte superior de una columna significa que en esa columna hay un conjunto de dos cuadrados verdes en vertical."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Notará que algunas filas/columnas tienen 2 números. \nSi ve '2 1', que le dice que en algún lugar de esa línea será una carrera de exactamente 2 cuadrados verdes, seguido de 1 o más cuadrados negros, seguidos de 1 cuadrado verde."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Haga clic con el botón izquierdo en un cuadrado para marcarlo en verde. Haga clic con el botón derecho para marcarlo con negro.\nEn nuestro sistema, los cuadrados negros representan los cuadrados vacíos o en blanco y los cuadrados verdes son los cuadrados codificados o rellenados.\nNo es necesario que rellene los cuadrados en blanco marcándolos si no lo desea. No es necesario para resolver el puzzle."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "Se recomienda encarecidamente que nunca adivine. Solo los cuadrados que se pueden determinar por la lógica deben codificarse o llenarse de color verde. \nEs fácil que un solo error provoque imprecisiones en todo el rompecabezas.\nLos rompecabezas sencillos pueden resolverse normalmente averiguando el razonamiento y centrándose en una sola fila/columna cada vez. A continuación, pasa a la siguiente fila hasta que haya llenado todas las casillas verdes."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Algunos rompecabezas más desafiantes también pueden requerir varios tipos de razonamiento que incluyen más de una fila (o columna). \nPuedes pensar que tienes la respuesta correcta para una fila, pero tu respuesta puede no funcionar para una columna de intersección. Resolver estas contradicciones es clave para resolver rompecabezas más complicados.\nCuando una celda no puede ser un cuadrado codificado/verde porque alguna otra celda produciría un error, debe ser un cuadrado negro/en blanco - y viceversa.\n\nCuando estés seguro de tu solución, haz clic en la marca de verificación para enviar el programa a revisión de código."

