translate spanish strings:

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:48
    old "Your goal in these puzzles is to fill the whole grid with green and black squares.\n\nAbove and to the left of the grid are numbers. These are the indicator numbers that tell you the number of green squares in that specific row and column.\n\nExample. If the row has a '3' next to it, that means there will be a set of three green (connected) squares somewhere in that row. It is the same for columns based on the numbers at the top of the puzzle. A '2' at the top of a column means that in that column, there is a set of two green squares running vertically."
    new "Tu objetivo en estos rompecabezas es llenar toda la cuadrícula con cuadros verdes y negros.\n\nEncima y a la izquierda de la cuadrícula verás números. Estos números indican cuántos cuadros verdes tiene cada fila y cada columna.\n\nPor ejemplo: si una fila tiene un ‘3’ al lado, significa que habrá un grupo de tres cuadros verdes (conectados) en algún punto de esa fila. Lo mismo ocurre con las columnas según los números en la parte superior del rompecabezas. Un ‘2’ arriba de una columna indica que en esa columna hay un grupo de dos cuadros verdes colocados verticalmente."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:53
    old "You will notice some rows/columns have 2 numbers.\n\nIf you see '2 1', that tells you that somewhere in that line will be a run of exactly 2 green squares, followed by 1 or more black squares, followed by 1 green square.\n\nThere might be black squares before or after the green squares - only the runs of green squares are counted."
    new "Notarás que algunas filas o columnas tienen dos números.\n\nSi ves ‘2 1’, significa que en esa línea habrá un grupo de exactamente 2 cuadros verdes, seguido por uno o más cuadros negros, y luego otro grupo de 1 cuadro verde.\n\nPuede haber cuadros negros antes o después; solo cuentan los grupos de cuadros verdes."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:58
    old "Left-click on a square to make it green. Right-click to mark with black.\n\nIn our system, the black squares represent the empty or blank squares and the green squares are the coded or filled squares.\n\nYou do not need to fill in the blank squares by marking them if you do not want to. It is not required to solve the puzzle."
    new "Haz clic izquierdo en un cuadro para marcarlo en verde. Haz clic derecho para marcarlo en negro.\n\nEn este sistema, los cuadros negros representan los espacios vacíos y los cuadros verdes son los cuadros codificados o rellenados.\n\nNo necesitas marcar los cuadros vacíos si no quieres; no es obligatorio para resolver el rompecabezas."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:63
    old "It is strongly advised never to guess. Only squares that can be determined by logic should be coded or filled green.\n\nIt is easy for a single error to cause inaccuracies across the entire puzzle.\n\nSimple puzzles can usually be solved by figuring out the reasoning by focusing on a single row/column at a time. Then move to the next row and the next row until you have filled all the green squares."
    new "Se recomienda encarecidamente no adivinar. Solo deben marcarse en verde los cuadros que puedas determinar mediante lógica.\n\nUn solo error puede causar fallos en todo el rompecabezas.\n\nLos rompecabezas simples suelen resolverse analizando una fila o columna a la vez. Luego continúa con la siguiente hasta completar todos los cuadros verdes."

    # game/code/minigames/nonogram/nonogram_tutorial.rpy:68
    old "Some more challenging puzzles may also require several types of reasoning that include more than one row (or column).\n\nYou might think that you have the correct answer for one row, but your answer might not work for an intersecting column. Resolving these contradictions is key to solving more complicated puzzles.\n\nWhen a cell cannot be a coded/green square because some other cell would produce an error, it should be a black/blank square - and vice versa.\n\nWhen you are confident in your solution, click the checkmark to submit the program for code review."
    new "Algunos rompecabezas más complejos pueden requerir distintos tipos de razonamiento que involucren más de una fila o columna.\n\nPuedes creer que resolviste correctamente una fila, pero tu solución puede entrar en conflicto con una columna que se cruza con ella. Resolver estas contradicciones es clave para los puzzles más avanzados.\n\nCuando una celda no puede ser verde porque generaría un error en otra parte, entonces debe ser negra, y viceversa.\n\nCuando estés seguro de tu solución, haz clic en la marca de verificación para enviarla a revisión."

